### ISSUE TITLE
Could not find generator

### ISSUE THREAD

**Issue by ingedmundo** [solidusio-contrib/solidus_klaviyo#19]
Hi! Im getting this error when trying to run  the install generator
`Could not find generator 'solidus_klaviyo:install'. Maybe you meant "solidus_reviews:install"?`

what it weird is that it is listed on the generator 
![image](https://user-images.githubusercontent.com/1649055/100764373-e2172280-33bb-11eb-81a4-0dd871754e15.png)

its also not showing if I run `gem list solidus`

Also tried running the install on solidus_tracking but had the same luck.
Is there something Im missing?

**Comment by andrewlynch** [comment]
I'm experiencing this same issue
